services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tenpo-pt-frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_BACKEND_URL: http://backend:8080
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
